import SessionProvider from "@/components/SessionProvider"
import SiteHeader from "@/components/SiteHeader"
import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next"
import { getServerSession } from "next-auth/next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="mx-auto max-w-5xl gap-2">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  )
}
